### ISSUE TITLE
Importing files of subfolder of subfolder of subfolder

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#47] opened 2019-11-14 20:09 UTC
My filetree:
spt
|     spt1
|     |       spt2
|     |     |     |     spt3
|     |     |     |     |     test.txt

But test.txt werent imported

**Comment by spck-io** [comment] 2019-11-27 15:57
Sorry, took me a while to figure out what was run. This bug was caused by an unintended race condition in the import zip feature which should have be fixed now. Let me know here if you’re still having problems.

**Closed by spck-io** 2019-11-27 15:57 UTC
