### ISSUE TITLE
Android: Keyboard IME not allowed making it impossible to type in Korean/Other Languages

### ISSUE THREAD

**Issue by day7500** [spckio/spck-issues#2] opened 2018-10-23 14:58 UTC
Hello, thank you for making a good app.
Find a bug in use to write.

There is a problem where Korean is not being entered.(한글)
And I would like to be personally supported for "php" automatic completion.

We look forward to a great app and we'll make sure to buy it when it's complete.

**Comment by spck-io** [comment] 2018-10-25 14:16
The editor has disabled IME inputs because in my previous experience with Google Keyboard, they have caused unexpected behaviors when editing the file. For example, the letters are 1 stroke delayed, meaning the characters only appear after typing a 2nd character.

This did not happen with other Android keyboards that I've tested, only the GBoard. I will investigate if it's possible to support the Keyboard's IME behavior without introducing this nasty problem in GBoard...

**Comment by spck-io** [comment] 2018-11-08 05:39
Fixed in Android app v1.2.3

**Closed by spck-io** 2018-11-08 05:39 UTC
Labels: android, enhancement
