### ISSUE TITLE
404 on Web App

### ISSUE THREAD

**Issue by SoerenSofke** [spckio/spck-issues#328] opened 2021-05-08 17:42 UTC
Dear Spck team,

your web editor is great and I use it very often on a regular PC (Windows or Linux type). I want to introduce it in classes and the students are using Chromebooks, where we found a showblocker: On all Chromebooks we have tested so far we see error 404 when using the web edition of Speck editor and preview e.g. an ordinary HTML project. Please find a screenshot attached.

This issue is present in normal browsing mode, in incognito mode and even in guest mode where no additional plugins are active. No special configuration is applied to the chromebooks. We also tested with a vanilla system.

Looking forward to learn on how to overcome this issue.

Best, Sören

![image](https://user-images.githubusercontent.com/16596310/117548384-01823d80-b035-11eb-8042-e4a65fb18955.png)

**Comment by SoerenSofke** [comment] 2021-05-16 19:16
Meanwhile I can confirm that 404 issue is present not only on Chromebooks but also an a verity of other operating systems / web browsers. We have seen it on Firefox (clean install), MS Edge (clean install), Chrome (clean install), multiple domains and multiple operating systems (Windows and Linux).

**Comment by Proxtx** [comment] 2021-05-26 13:30
Hey Sören. This seems to be an issue with the implementation of indexdb. Spck is supposed to send you the files / page when going to the subdomain "/run/idb/". I experienced this issue myself.... I think its caused by the implmentation of the saving / loading system on android / ios. It probably overwrote the web save implementation. I dont think there will be a fix soon becuase the dev hasn't been active 4 Months.

**Comment by SoerenSofke** [comment] 2021-05-26 15:52
👍

**Comment by Proxtx** [comment] 2021-12-16 15:22
@SoerenSofke This is fixed now.

**Closed as completed** 2022-01-03 23:00 UTC
