### ISSUE TITLE
Importing Zip files only working sometimes

### ISSUE THREAD

**Issue by Proxtx** [spckio/spck-issues#58] opened 2019-12-07 21:01 UTC
90% of my trys to import a zip file are failing.

**Comment by Proxtx** [comment] 2019-12-07 21:55
PS also not working with Browser / Chrome (IDB)

**Comment by spck-io** [comment] 2019-12-11 21:07
I am unable to replicate this, could you explain how you generate the zip file or provide a sample zip file that doesn’t work? I know there are some problems with the zip library jszip, it is no longer being worked on, therefore I need to fork and make a fix for it.

**Comment by spck-io** [comment] 2020-01-14 17:05
Closing this as a duplicate of #49, I changed the zip library to use zip.js which seems to handle more edge cases in zip file import.

**Closed by spck-io** 2020-01-14 17:05 UTC
